import React from 'react'

const AustraliaSyllabus = () => {
    const ibSylabus = [
        {
            subject: "Biology",
            topics: [
                "Cellular Respiration",
                "Understanding Aerobic Respiration",
                "Chemical Equations of Respiration",
                "Understanding Anaerobic Respiration",
                "Chemical Equations and Muscle Fatigue",
                "Understanding Photosynthesis",
                "Role of Chlorophyll in Photosynthesis",
                "Photosynthesis Subsequent Processes",
                "Investigating Photosynthesis Factors",
                "Features of Leaves and Photosynthesis Adaptations",
                "Identifying Leaf Structure",
                "Structural Adaptations for Photosynthesis",
                "DNA and Classification",
                "Evolutionary Relationships",
                "Binomial System of Nomenclature",
                "Plant and Animal Cell",
                "Structure of a Bacterial Cell",
                "Functions of Cell Structure",
                "Cell Division and New Cell Production",
                "Specialized Cells and Their Functions",
                "Exploring the Circulatory System",
                "Anatomy of the Mammalian Heart",
                "Anatomy of Blood Vessels",
                "Functions of Digestive System Organs",
                "Detailed Kidney and Nephron Structure and Function",
                "Excretion in Humans",
                "Understanding Neuronal Impulse Transmission",
                "Immunity, Vaccination, and Passive Immunity",
                "Understanding Pathogens and Disease Transmission",
                "Body Defenses and Disease Control Measures",
                "Understanding Catalyst and Enzymes",
                "Investigating Enzyme Activity",
                "Enzyme Specificity and Action",
                "Functions of Xylem and Phloem",
                "Mechanism of Water Movement in Xylem",
                "Understanding Transpiration",
                "Investigating Transpiration Rates",
                "Structure of DNA Molecule",
                "Species and Reproduction",
                "Detailed Kidney and Nephron Structure and Function",
                "Liver Function and Systemic Importance of Excretion",
                "Understanding Neuronal Impulse Transmission",
                "Uses of Energy in Living Organisms",
                "Understanding a Balanced Diet",
                "Organs of the Digestive System",
                "Functions of Digestive System Organs",
                "Physical and Chemical Digestion",
                "Role of Bile in Emulsifying Fats",
                "Enzymatic Functions in Digestion",
                "Absorption of Nutrients and Water",
                "Structure and Function of a Villus",
                "Double Circulation in Mammals",
                "Anatomy of the Mammalian Heart",
                "Anatomy of Blood Vessels",
                "Components and Functions of Blood",
                "Features of Gas Exchange Surfaces",
                "Investigating Respiratory Changes",
                "Breathing Mechanisms and Functions",
                "Diffusion in Living Organisms",
                "Understanding Osmosis",
                "Active Transport in Biological Processes",
                "Role of Water in Organisms",
                "Investigating Osmosis with Dialysis Tubing",
                "Effect of Osmosis on Plant Tissue",
                "Understanding Osmosis Through Water Potential",
                "Classification of Organisms in Groups",
                "The Five Kingdoms of Life",
                "Groups Within the Animal Kingdom (Vertebrates and Arthropods)",
                "Groups Within Plant Kingdom (Ferns and Flowering Plants)",
                "Understanding Ammonium Salts and Nitrates in Fertilizers",
                "Exploring NPK Fertilisers",
                "Exploring States of Matter and Transformation",
                "Effect of Temperature and Pressure on Gas Volume",
                "Visualizing Change of State",
                "Understanding Diffusion",
                "Molecular Mass and Diffusion Rate",
                "Defining Isotopes",
                "Chemical Properties of Isotopes",
                "Calculating Relative Atomic Mass",
                "Testing for the Presence of Water",
                "Understanding Water Composition and Treatment",
                "Understanding Catalysts in Reactions",
                "Fundamentals of Hydrogen-Oxygen Fuel Cells",
                "Comparing Fuel Cells and Gasoline Engines",
                "Naming and Drawing Key Organic Molecules",
                "Constructing and Naming Unbranched Esters",
                "Constructing Structural Formulae and Identifying Isomers",
                "Classifying Organic Compounds by Name and Structure"
            ]
        },
        {
            subject: "Chemistry",
            topics: [
                "Constructing Chemical Equations",
                "Calculating Reacting Masses in Proportions",
                "Understanding Concentration Units",
                "Exploring the Mole and Avogadro’s Constant",
                "Applying Mole Concept to Gas Volumes and Solutions",
                "Reaction of acid with metal",
                "Reaction of acid with base",
                "Reaction of acid with carbonates",
                "Acid and Base Dissociation",
                "Classifying Oxides",
                "Exploring Amphoteric Oxides",
                "Preparing Soluble Salts - Titration Reaction",
                "Atomic, Mass Numbers and Electron Configuration",
                "Identifying Elements, Compounds and Mixtures",
                "Relative Charges and Masses",
                "Defining Isotopes",
                "Calculating Relative Atomic Mass",
                "Formation of Cations and Anions",
                "Exploring Atom Structure",
                "Understanding Ionic Bonds",
                "Introduction to Covalent Bonds",
                "Formation of Simple Covalent Molecules",
                "Understanding Metallic Bonding",
                "Giant Covalent Structure of Silicon(IV) Oxide",
                "Fundamentals of Electrolysis",
                "Applications of Electrolysis in Electroplating",
                "Hydrogen-Oxygen Fuel Cells",
                "Comparing Fuel Cells and Gasoline Engines",
                "Understanding Exothermic and Endothermic Reactions",
                "Reaction Pathway Diagrams",
                "Factors Affecting Reaction Rates",
                "Understanding Catalysts in Reactions",
                "Collision Theory and Reaction Rates",
                "Basics of Reversible Reactions",
                "Chemical Equilibrium in Closed Systems",
                "Factors Influencing Equilibrium",
                "Understanding Redox Reactions and Oxidation Numbers",
                "Electron Transfer in Redox Reactions",
                "Testing Water Purity",
                "Understanding Solutions and Mixtures",
                "Precipitation and Water of Crystallization",
                "Understanding Polymer Structures and Polymerization Types",
                "Analyzing the Composition of Air",
                "Investigating Air Pollutants and Their Effects",
                "Metal Extraction from Ores",
                "Blast Furnace and Iron Extraction",
                "Extracting Aluminium from Bauxite",
                "Galvanizing and Sacrificial Protection",
                "Rusting of Iron and Steel",
                "Understanding Reactivity Series",
                "Metal Reactivity Through Displacement Reactions",
                "Oxide Layer of Aluminium",
                "Fractional Distillation of Petroleum",
                "Applications of Petroleum Fractions",
                "Introduction to Fossil Fuels and Petroleum Components",
                "Exploring NPK Fertilisers"
            ]
        },
        {
            subject: "Physics",
            topics: [
                "Scalar and Vector Quantities",
                "Gravitational Force on Surface of Moon and Earth",
                "Terminal Velocity",
                "Exploring Density Fundamentals",
                "Measuring Density of Different Materials",
                "Effects of Forces",
                "Determining Resultant Forces",
                "Motion and Friction",
                "Circular Motion and Force Acceleration Relationship",
                "Exploring Momentum",
                "Impulse",
                "Conservation of Momentum",
                "Energy Transfer and Conservation",
                "Calculating Kinetic Energy",
                "Exploring Energy Resources",
                "Understanding Energy Efficiency",
                "Fundamentals of Work",
                "Exploring the Concept of Power",
                "Measuring Specific Heat Capacity",
                "Understanding Thermal Conduction Mechanisms",
                "Principle of Convection in Liquids and Gases",
                "Fundamentals of Thermal Radiation",
                "Basic Concepts of Waves",
                "Reflection, Refraction, and Diffraction of Waves",
                "Electromagnetic Spectrum Regions and Uses",
                "Health Effects and Communication Systems",
                "Basic Concepts of Magnetism",
                "Practical Applications of Magnetism",
                "Exploring Electromagnetic Induction",
                "Applications of Electromagnetism",
                "Fundamentals of Electric Current",
                "Exploring EMF and PD Concepts",
                "Measurement of EMF and PD",
                "Understanding and Measuring Resistance",
                "Calculation of Electrical Power and Energy",
                "Principles of Series and Parallel Circuits",
                "Advanced Calculations and Practical Applications",
                "Understanding D.C. Motor Mechanics",
                "Operation of Electric Motors and Components",
                "Understanding A.C. Generators",
                "Transformer Construction and Basic Principles",
                "Measuring Distance",
                "Measuring Speed",
                "Concept of Spring Constant",
                "Understanding Moment of a Force",
                "Applying the Principle of Moments",
                "Experiment Demonstrating Equilibrium",
                "Understanding the Centre of Gravity",
                "Finding the Centre of Gravity in Irregular Objects",
                "Centre of Gravity and Stability",
                "Resultant Force and Momentum Change",
                "Exploring the Concept of Pressure",
                "Pressure in Liquids",
                "Pressure and Particle Motion in Gases",
                "Particle Structure of Matter",
                "Particle Motion and Temperature",
                "Brownian Motion and Particle Dynamics",
                "Effect of Temperature and Volume Changes on Gas",
                "Understanding Kelvin and Celsius Scales",
                "Exploring Thermal Expansion in Solids, Liquids, and Gases",
                "Applications and Consequences of Thermal Expansion"
            ]
        }
    ];

    return (
        <div className='countryListPageMain sylabusListMain'>
            <div className="padding-lr-class margin-top-100-class">
                <div className="countryListPage">
                    <div className="d-flex gap-5 pt-5 pb-3 align-items-center">
                        <h4 className='pageHeadText'><img src="/img/country/australia.svg" alt="" /> Australian Curriculum</h4>
                    </div>
                    <hr className='mb-5' />
                    <div className="countryListPageGrid pb-5">
                        {ibSylabus.map((val, index) => (
                            <div className='countryListInner' key={index}>
                                <h2>{val.subject}</h2>
                                <ul>
                                    {val.topics.map((val) => (
                                        <li key={val}>{val}</li>
                                    ))}
                                </ul>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    )
}

export default AustraliaSyllabus