import React from 'react'

const USSyllabus = () => {
    const ibSylabus = [
        {
            subject: "Biology",
            topics: [
                "Cellular respiration (aerobic and anaerobic)",
                "Plant and animal cells",
                "Structure of a bacterial cell",
                "Cell division (mitosis and introduction to meiosis)",
                "Specialized cells and their functions",
                "Functions of cell structure",
                "Diffusion, osmosis, and active transport",
                "Structure and function of DNA",
                "Hierarchy: cell to organism",
                "Enzyme specificity and activity",
                "Understanding catalysts and enzymes",
                "Structure of DNA molecule",
                "DNA and classification",
                "Species and reproduction",
                "Evolutionary relationships",
                "Binomial system of nomenclature",
                "Dichotomous keys",
                "Kingdom classification (including five kingdoms of life)",
                "Natural selection and adaptation",
                "Understanding photosynthesis",
                "Role of chlorophyll in photosynthesis",
                "Investigating photosynthesis factors",
                "Structural adaptations for photosynthesis",
                "Leaf structure and adaptations",
                "Transport systems in plants (xylem, phloem)",
                "Transpiration and water movement in plants",
                "Digestive system (organs and their functions)",
                "Enzymatic functions in digestion",
                "Role of bile and hydrochloric acid in digestion",
                "Nutrient and water absorption",
                "Circulatory system (including heart anatomy, single and double circulation, blood vessels)",
                "Components of blood and their functions",
                "Clotting process",
                "Respiratory system (gas exchange surfaces, breathing mechanics)",
                "Excretory system (detailed kidney and nephron structure, liver function)",
                "Neuronal impulse transmission (basic understanding of nervous system functions)",
                "Chemical elements in carbohydrates, fats, and proteins",
                "Formation of large molecules",
                "Investigating enzyme activity",
                "Testing for biological molecules",
                "Role of water in organisms",
                "Pathways of water through plants",
                "Investigating transpiration rates and mechanisms",
                "Understanding pathogens and disease transmission",
                "Immunity, vaccination, and passive immunity",
                "Body defenses and disease control measures",
                "Functions of blood components",
                "Anatomy of the mammalian heart",
                "Monitoring heart activity",
                "Investigating the impact of physical activity on heart rate",
                "Chemical equations of respiration (aerobic and anaerobic)",
                "Classification of organisms in groups",
                "The five kingdoms of life",
                "Evolutionary relationships and DNA-based classification",
                "Binomial nomenclature and its application in classifying species",
                "Dichotomous keys for identifying species",
                "Structure of xylem vessels and their function in water transport",
                "Root hair cells and their role in water and nutrient absorption",
                "Translocation in plants, describing sources and sinks",
                "Investigating water pathways in plants",
                "Mechanism of water movement through xylem",
                "Effects of osmosis on plant tissue (investigating with dialysis tubing)",
                "Single and double circulation in animals (comparison between fish and mammals)",
                "Anatomy of blood vessels and their adaptations to function",
                "Gas exchange surfaces and their role in respiration",
                "Respiratory changes and structural dynamics of breathing",
                "Chemical equations and the role of energy in aerobic and anaerobic respiration",
                "Detailed structure and function of the kidney and nephron",
                "Excretion in humans, including the role of the liver in detoxification",
                "Investigating factors that influence homeostasis (e.g., temperature regulation, water balance)",
                "Understanding neuronal impulse transmission",
                "Basic structure and function of neurons",
                "Role of the nervous system in maintaining homeostasis and responding to stimuli",
                "Investigating respiration in yeast (anaerobic respiration)",
                "Chemical equations related to aerobic and anaerobic respiration",
                "Understanding muscle fatigue and its relationship with anaerobic respiration",
                "Investigating factors influencing diffusion and osmosis",
                "Investigating enzyme activity and enzyme specificity",
                "Investigating photosynthesis and the role of chlorophyll",
                "Investigating transpiration rates and water movement in plants",
                "Understanding and applying the magnification formula for cellular structures"
            ]
        },
        {
            subject: "Chemistry",
            topics: [
                "Constructing and balancing chemical equations",
                "Calculating reacting masses and proportions",
                "Understanding concentration units (molarity)",
                "The mole concept and Avogadro's constant",
                "Applying the mole concept to gas volumes and solutions",
                "Reaction of acids with metals, bases, and carbonates",
                "Acid dissociation and base dissociation (strong vs. weak acids/bases)",
                "Proton donors and acceptors",
                "Classifying oxides (acidic, basic, amphoteric)",
                "Preparing soluble salts through titration reactions",
                "pH indicators like litmus, thymolphthalein, and methyl orange",
                "Fundamentals of electrolysis and applications (electroplating)",
                "Advanced dynamics of electrolysis",
                "Hydrogen-oxygen fuel cells",
                "Redox reactions, oxidation numbers, and electron transfer",
                "Identifying oxidizing and reducing agents",
                "Understanding exothermic and endothermic reactions",
                "Collision theory and factors affecting reaction rates",
                "Reversible reactions and chemical equilibrium",
                "Factors influencing equilibrium (Le Chatelier's Principle)",
                "Atomic structure, mass numbers, and electron configuration",
                "Understanding isotopes and calculating relative atomic mass",
                "Ionic and covalent bonds (properties of ionic and covalent compounds)",
                "Metallic bonding and properties of metals",
                "Molecular mass and diffusion rate",
                "Introduction to organic molecules (alkanes, alkenes, and alcohols)",
                "Homologous series and functional groups",
                "Saturated and unsaturated compounds (alkanes vs. alkenes)",
                "Structural formulas, isomers, and nomenclature of organic compounds",
                "Formation of esters, polymers, and properties of plastics",
                "Formation of ionic compounds and properties of ionic bonding",
                "Formation of simple covalent molecules and properties of covalent bonds",
                "Understanding the giant covalent structures (e.g., silicon(IV) oxide, graphite, and diamond)",
                "Relating the structures of graphite and diamond to their uses",
                "Understanding metallic bonding and the structure of metals",
                "Basics of reversible reactions",
                "Chemical equilibrium in closed systems",
                "Introduction to fossil fuels and the structure of alkanes",
                "Reactivity of alkanes and substitution reactions",
                "Introduction to alkenes and their double bonds",
                "Testing for unsaturated hydrocarbons (alkenes)",
                "Manufacturing ethene by cracking alkanes",
                "Reactivity of carboxylic acids (ethanoic acid) and ester formation",
                "Natural polymers (e.g., proteins) and synthetic polymers (e.g., polyethylene)",
                "Properties and disposal of plastics",
                "Water composition, treatment, and testing water purity",
                "Investigating air pollutants and their effects",
                "NPK fertilizers and the role of ammonium salts in fertilizers",
                "Reactivity series and metal displacement reactions",
                "Extraction of metals (iron from blast furnace, aluminum from bauxite)",
                "Rusting of iron and methods for prevention (galvanizing and sacrificial protection)",
                "Exploring states of matter and changes in state",
                "Understanding solutions, mixtures, and solubility",
                "The role of catalysts in chemical reactions"
            ]
        },
        {
            subject: "Physics",
            topics: [
                "Scalar and vector quantities",
                "Measuring length, volume, time, distance, speed, temperature, mass, and weight",
                "Gravitational force on the surface of the Moon and Earth",
                "Measuring density of different materials",
                "Terminal velocity",
                "Effects of forces",
                "Concept of spring constant",
                "Resultant forces",
                "Circular motion and force-acceleration relationship",
                "Motion and friction",
                "Understanding momentum, impulse, and conservation of momentum",
                "Resultant force and momentum change",
                "Identifying different forms of energy",
                "Energy transfer and conservation",
                "Calculating kinetic energy",
                "Fundamentals of work",
                "Exploring energy resources (solar, wind, hydropower, geothermal, biomass, fossil fuels)",
                "Understanding energy efficiency",
                "Exploring the concept of power",
                "Exploring the concept of pressure",
                "Pressure in liquids",
                "Exploring properties of solids, liquids, and gases",
                "Understanding change of state",
                "Particle structure and motion of matter",
                "Brownian motion and particle dynamics",
                "Pressure and particle motion in gases",
                "Kelvin and Celsius temperature scales",
                "Thermal expansion in solids, liquids, and gases",
                "Thermal conduction, convection, and radiation",
                "Measuring specific heat capacity",
                "Internal energy and temperature rise",
                "Basic concepts of waves (transverse and longitudinal)",
                "Reflection, refraction, and diffraction of waves",
                "Sound production, properties, and advanced sound concepts (including ultrasound)",
                "Electromagnetic spectrum regions and uses",
                "Health effects and communication systems",
                "Light reflection and refraction",
                "Refractive index and optical fibers",
                "Thin lenses and their applications",
                "Dispersion through a prism",
                "Monochromatic light",
                "Basics of electric charge and electrostatics",
                "Electric fields and field patterns",
                "Fundamentals and advanced concepts of electric current",
                "EMF and potential difference (PD)",
                "Understanding and measuring resistance",
                "Series and parallel circuits",
                "Electrical energy transfer and power calculations",
                "Circuit diagrams and components (including diodes and LEDs)",
                "Investigating the impact of physical activity on heart rate",
                "Variable potential dividers",
                "Basic concepts and practical applications of magnetism",
                "Electromagnetic induction (including quantitative aspects)",
                "Understanding impulse and its relation to momentum",
                "Conservation of momentum in different scenarios",
                "Complex energy conservation scenarios",
                "Application of the principle of moments to equilibrium and stability in systems",
                "Center of gravity and finding the center of gravity in irregular objects",
                "Detailed exploration of energy resources, including renewable and non-renewable sources",
                "Complex applications of thermal energy transfer",
                "Understanding electrical hazards, wiring, and protection devices",
                "Directionality and quantitative aspects of induction in electromagnetic systems"
            ]
        }
    ];

    return (
        <div className='countryListPageMain sylabusListMain'>
            <div className="padding-lr-class margin-top-100-class">
                <div className="countryListPage">
                    <div className="d-flex gap-5 pt-5 pb-3 align-items-center">
                        <h4 className='pageHeadText'><img src="/img/country/usa.svg" alt="" /> Common Core State Standards & Next Generation Science Standards</h4>
                    </div>
                    <hr className='mb-5' />
                    <div className="countryListPageGrid pb-5">
                        {ibSylabus.map((val, index) => (
                            <div className='countryListInner' key={index}>
                                <h2>{val.subject}</h2>
                                <ul>
                                    {val.topics.map((val) => (
                                        <li key={val}>{val}</li>
                                    ))}
                                </ul>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    )
}

export default USSyllabus